---
- hosts: all
  gather_facts: no
  # serial: 1

  vars_prompt:
    - name: must_have_groups
      prompt: "Enter the must-have groups as regex (e.g., us_.*,cisco.*)"
      private: no
    - name: optional_groups
      prompt: "Enter optional groups as regex, at least one must be present (e.g., poe_switch.*,access_switch.*)"
      private: no
    - name: vlan_id
      prompt: "Enter the VLAN ID"
      private: no
    - name: template_name
      prompt: "Enter the template name (e.g., cisco_cat, cisco_sg)"
      private: no
  
  vars:
    template_base_path: "../templates/show_vlan"
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    must_have_groups_list: "{{ must_have_groups.split(',') }}"
    optional_groups_list: "{{ optional_groups.split(',') }}"
  vars_files:
    - creds.yml
  
  tasks:
    - name: Include dir management tasks
      include_tasks: tasks/dir_management.yml

    - name: Include dynamic group setup tasks
      include_tasks: tasks/setup_dynamic_group.yml

    - name: Conditionally include template command execution tasks
      include_tasks: tasks/template_command_execution.yml
      when: is_dynamic_group_member | default(false)
