---
- hosts: all
  gather_facts: no
  # serial: 1

  vars_prompt:
    - name: must_have_groups
      prompt: "Enter the must-have groups as regex (e.g., us_.*,cisco.*)"
      private: no
    - name: optional_groups
      prompt: "Enter optional groups as regex, at least one must be present (e.g., poe_switch.*,access_switch.*)"
      private: no
    - name: template_name
      prompt: "Enter the template name"
      private: no
    - name: interface_type
      prompt: "Enter the interface type(s) separated by comma (or 'any' for all types)"
      private: no
    - name: interface_mode
      prompt: "Enter the interface mode(s) separated by comma (or 'any' for all modes)"
      private: no
  
  vars:
    template_base_path: "../templates/shri"
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
  
  vars_files:
    - creds.yml
  
  tasks:
    - name: Include dir management tasks
      include_tasks: tasks/dir_management.yml

    - name: Include dynamic group setup tasks
      include_tasks: tasks/setup_dynamic_group.yml

    - name: Include select specific interfaces tasks
      include_tasks: tasks/select_specific_interfaces.yml
      when: is_dynamic_group_member | default(false)
    
    - name: Conditionally include template command execution tasks
      include_tasks: tasks/template_command_execution.yml
      when: is_dynamic_group_member | default(false)
